spring.application.name=authn
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-lively-sun-aifo35gz-pooler.c-4.us-east-1.aws.neon.tech/authn?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wlkJ1dCbx2hz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=mySuperSecretKeyForJWTTokenGenerationAndValidation2024
jwt.expiration=7200000
